__default__:
    partition: "hh"
    time: 120 # default time (minutes)
    nodes: 1
    ntasks: 2
    mem: "8G" # default memory
    output: "logs/{rule}_{wildcards.tshort}.out"
    error: "logs/{rule}_{wildcards.tshort}.err"
    # job-name: "{rule}_{wildcards.tshort}"
